### ISSUE TITLE
Simulación de Esfuerzos Mecánicos

### ISSUE THREAD

**Issue by nardyliz12** [nardyliz12/Proyectos_Para_Ingenieria_1#8]

**Comment by erickalarcn** [comment]
Se requiere hacer nuevas simulaciones de esfuerzos mecánico; ya que, este depende del chasís del dispositivo. Por ello, las pruebas anteriores de tracción y compresión, se realizarán nuevamente al igual que se añadirán nuevas simulaciones para situaciones reales como una simulación para una posible caída del dispositivo o las deformaciones que puede sufrir este.
